services:
  auth-service:
    env_file:
      - ./.env
    build:
      context: .
    container_name: e-commerce-auth-service
    ports:
      - 3000:3000
    networks:
      - e-commerce-network
networks:
  e-commerce-network:
    external: true